FROM ubuntu:18.04
#RUN apt-get update && \
#    apt-get install -y --no-install-recommends curl ca-certificates jq iproute2 vim-tiny less bash-completion unzip && \
#    curl -sLf https://get.docker.com/builds/Linux/x86_64/docker-1.10.3 > /usr/bin/docker && \
#    chmod +x /usr/bin/docker && \
#    curl -sLf https://storage.googleapis.com/kubernetes-release/release/v1.10.5/bin/linux/amd64/kubectl > /usr/bin/kubectl && \
#    chmod +x /usr/bin/kubectl && \
#    DEBIAN_FRONTEND=noninteractive apt-get autoremove -y && \
#    DEBIAN_FRONTEND=noninteractive apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl ca-certificates jq iproute2 vim-tiny less bash-completion unzip 

ENV LOGLEVEL_VERSION v0.1
#RUN curl -sLf https://github.com/rancher/loglevel/releases/download/${LOGLEVEL_VERSION}/loglevel-amd64-${LOGLEVEL_VERSION}.tar.gz | tar xvzf - -C /usr/bin
#RUN curl -sL https://github.com/rancher/share-mnt/releases/download/v1.0.3/share-mnt.tar.gz | tar xvzf - -C /usr/bin
#RUN curl -sL https://github.com/c-bata/kube-prompt/releases/download/v1.0.3/kube-prompt_v1.0.3_linux_amd64.zip > /usr/bin/kube-prompt.zip && unzip /usr/bin/kube-prompt.zip -d /usr/bin

COPY docker kubectl loglevel-amd64-v0.1.tar.gz share-mnt.tar.gz kube-prompt.zip /tmp/

RUN cp /tmp/docker /tmp/kubectl /usr/bin/ && \
    tar xvzf /tmp/loglevel-amd64-v0.1.tar.gz -C /usr/bin && \
    tar xvzf /tmp/share-mnt.tar.gz -C /usr/bin && \
    unzip /tmp/kube-prompt.zip -d /usr/bin && \
    chmod +x /usr/bin/docker && \
    chmod +x /usr/bin/kubectl && \
    DEBIAN_FRONTEND=noninteractive apt-get autoremove -y && \
    DEBIAN_FRONTEND=noninteractive apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ARG VERSION=dev
LABEL io.cattle.agent true
ENV DOCKER_API_VERSION 1.24
ENV AGENT_IMAGE rancher/rancher-agent:${VERSION}
ENV SSL_CERT_DIR /etc/kubernetes/ssl/certs
COPY agent run.sh kubectl-shell.sh shell-setup.sh share-root.sh /usr/bin/
ENTRYPOINT ["run.sh"]
